apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: bankapp-destination
spec:
  host: bankapp-service
  subsets:
  - name: blue
    labels:
      version: blue
  - name: green
    labels:
      version: green
