apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bankapp-vs
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio.gateway.name }}
  http:
  - route:
    - destination:
        host: bankapp-service
        subset: {{ .Values.activeColor }}
      weight: 100
